import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import QueryClientProvider from "@/providers/queryClient";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/toaster";
import AuthenticatedComponent from "./authenticated";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProvider>
            <AuthenticatedComponent>{children}</AuthenticatedComponent>
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
